<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property boolean $Adult
 * @property \DTS\eBaySDK\Trading\Types\AmountType $BestOfferAutoAcceptPrice
 * @property boolean $BindingAuction
 * @property boolean $BuyItNowAvailable
 * @property boolean $CheckoutEnabled
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConvertedBuyItNowPrice
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConvertedReservePrice
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConvertedStartPrice
 * @property \DTS\eBaySDK\Trading\Enums\EndReasonCodeType $EndingReason
 * @property \DateTime $EndTime
 * @property boolean $HasPublicMessages
 * @property boolean $HasReservePrice
 * @property boolean $HasUnansweredQuestions
 * @property string $LocalListingDistance
 * @property \DTS\eBaySDK\Trading\Types\AmountType $MinimumBestOfferPrice
 * @property string $RelistedItemID
 * @property string $SecondChanceOriginalItemID
 * @property \DateTime $StartTime
 * @property string $TCROriginalItemID
 * @property string $ViewItemURL
 * @property string $ViewItemURLForNaturalSearch
 */
class ListingDetailsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Adult' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Adult'
        ],
        'BestOfferAutoAcceptPrice' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoAcceptPrice'
        ],
        'BindingAuction' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BindingAuction'
        ],
        'BuyItNowAvailable' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyItNowAvailable'
        ],
        'CheckoutEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CheckoutEnabled'
        ],
        'ConvertedBuyItNowPrice' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConvertedBuyItNowPrice'
        ],
        'ConvertedReservePrice' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConvertedReservePrice'
        ],
        'ConvertedStartPrice' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConvertedStartPrice'
        ],
        'EndingReason' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EndingReason'
        ],
        'EndTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EndTime'
        ],
        'HasPublicMessages' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HasPublicMessages'
        ],
        'HasReservePrice' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HasReservePrice'
        ],
        'HasUnansweredQuestions' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HasUnansweredQuestions'
        ],
        'LocalListingDistance' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistance'
        ],
        'MinimumBestOfferPrice' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinimumBestOfferPrice'
        ],
        'RelistedItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RelistedItemID'
        ],
        'SecondChanceOriginalItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SecondChanceOriginalItemID'
        ],
        'StartTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StartTime'
        ],
        'TCROriginalItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TCROriginalItemID'
        ],
        'ViewItemURL' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ViewItemURL'
        ],
        'ViewItemURLForNaturalSearch' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ViewItemURLForNaturalSearch'
        ]
    ];
    
    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }
        
        $this->setValues(__CLASS__, $childValues);
    }
}