<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property boolean $AdditionalCompatibilityEnabled
 * @property \DTS\eBaySDK\Trading\Enums\AdFormatEnabledCodeType $AdFormatEnabled
 * @property boolean $BasicUpgradePackEnabled
 * @property boolean $BestOfferAutoAcceptEnabled
 * @property boolean $BestOfferAutoDeclineEnabled
 * @property boolean $BestOfferCounterEnabled
 * @property boolean $BestOfferEnabled
 * @property boolean $BrandMPNIdentifierEnabled
 * @property boolean $BuyerGuaranteeEnabled
 * @property boolean $ClassifiedAdAutoAcceptEnabled
 * @property boolean $ClassifiedAdAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ClassifiedAdBestOfferEnabledCodeType $ClassifiedAdBestOfferEnabled
 * @property boolean $ClassifiedAdCompanyNameEnabled
 * @property boolean $ClassifiedAdContactByAddressEnabled
 * @property boolean $ClassifiedAdContactByEmailEnabled
 * @property boolean $ClassifiedAdContactByPhoneEnabled
 * @property boolean $ClassifiedAdCounterOfferEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ClassifiedAdPaymentMethodEnabledCodeType $ClassifiedAdPaymentMethodEnabled
 * @property boolean $ClassifiedAdPayPerLeadEnabled
 * @property integer $ClassifiedAdPhoneCount
 * @property boolean $ClassifiedAdShippingMethodEnabled
 * @property integer $ClassifiedAdStreetCount
 * @property string $CompatibleVehicleType
 * @property \DTS\eBaySDK\Trading\Enums\ConditionEnabledCodeType $ConditionEnabled
 * @property \DTS\eBaySDK\Trading\Types\ConditionValuesType $ConditionValues
 * @property boolean $CrossBorderTradeAustraliaEnabled
 * @property boolean $CrossBorderTradeGBEnabled
 * @property boolean $CrossBorderTradeNorthAmericaEnabled
 * @property boolean $DepositSupported
 * @property boolean $DigitalGoodDeliveryEnabled
 * @property \DTS\eBaySDK\Trading\Types\DomesticRefundMethodCodeType $DomesticRefundMethodValues
 * @property \DTS\eBaySDK\Trading\Types\DomesticReturnsAcceptedCodeType $DomesticReturnsAcceptedValues
 * @property \DTS\eBaySDK\Trading\Types\DomesticReturnsDurationCodeType $DomesticReturnsDurationValues
 * @property \DTS\eBaySDK\Trading\Types\DomesticReturnsShipmentPayeeCodeType $DomesticReturnsShipmentPayeeValues
 * @property \DTS\eBaySDK\Trading\Enums\ProductIdentiferEnabledCodeType $EANEnabled
 * @property boolean $EANIdentifierEnabled
 * @property \DTS\eBaySDK\Trading\Enums\AdFormatEnabledCodeType $eBayMotorsProAdFormatEnabled
 * @property boolean $eBayMotorsProAutoAcceptEnabled
 * @property boolean $eBayMotorsProAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ClassifiedAdBestOfferEnabledCodeType $eBayMotorsProBestOfferEnabled
 * @property boolean $eBayMotorsProCompanyNameEnabled
 * @property boolean $eBayMotorsProContactByAddressEnabled
 * @property boolean $eBayMotorsProContactByEmailEnabled
 * @property boolean $eBayMotorsProContactByPhoneEnabled
 * @property boolean $eBayMotorsProCounterOfferEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ClassifiedAdPaymentMethodEnabledCodeType $eBayMotorsProPaymentMethodCheckOutEnabled
 * @property integer $eBayMotorsProPhoneCount
 * @property boolean $eBayMotorsProSellerContactDetailsEnabled
 * @property boolean $eBayMotorsProShippingMethodEnabled
 * @property integer $eBayMotorsProStreetCount
 * @property boolean $EpidSupported
 * @property boolean $FreeGalleryPlusEnabled
 * @property boolean $FreePicturePackEnabled
 * @property \DTS\eBaySDK\Trading\Types\ListingEnhancementDurationReferenceType $GalleryFeaturedDurations
 * @property boolean $GlobalShippingEnabled
 * @property \DTS\eBaySDK\Trading\Types\AmountType $Group1MaxFlatShippingCost
 * @property \DTS\eBaySDK\Trading\Types\AmountType $Group2MaxFlatShippingCost
 * @property \DTS\eBaySDK\Trading\Types\AmountType $Group3MaxFlatShippingCost
 * @property boolean $HandlingTimeEnabled
 * @property boolean $HomePageFeaturedEnabled
 * @property \DTS\eBaySDK\Trading\Enums\INEscrowWorkflowTimelineCodeType $INEscrowWorkflowTimeline
 * @property \DTS\eBaySDK\Trading\Types\InternationalRefundMethodCodeType $InternationalRefundMethodValues
 * @property \DTS\eBaySDK\Trading\Types\InternationalReturnsAcceptedCodeType $InternationalReturnsAcceptedValues
 * @property \DTS\eBaySDK\Trading\Types\InternationalReturnsDurationCodeType $InternationalReturnsDurationValues
 * @property \DTS\eBaySDK\Trading\Types\InternationalReturnsShipmentPayeeCodeType $InternationalReturnsShipmentPayeeValues
 * @property \DTS\eBaySDK\Trading\Enums\ProductIdentiferEnabledCodeType $ISBNEnabled
 * @property boolean $ISBNIdentifierEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ItemCompatibilityEnabledCodeType $ItemCompatibilityEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ItemSpecificsEnabledCodeType $ItemSpecificsEnabled
 * @property boolean $KTypeSupported
 * @property \DTS\eBaySDK\Trading\Types\ListingDurationReferenceType[] $ListingDuration
 * @property string $LocalListingDistancesNonSubscription
 * @property string $LocalListingDistancesRegular
 * @property string $LocalListingDistancesSpecialty
 * @property \DTS\eBaySDK\Trading\Enums\AdFormatEnabledCodeType $LocalMarketAdFormatEnabled
 * @property boolean $LocalMarketAutoAcceptEnabled
 * @property boolean $LocalMarketAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ClassifiedAdBestOfferEnabledCodeType $LocalMarketBestOfferEnabled
 * @property boolean $LocalMarketCompanyNameEnabled
 * @property boolean $LocalMarketContactByAddressEnabled
 * @property boolean $LocalMarketContactByEmailEnabled
 * @property boolean $LocalMarketContactByPhoneEnabled
 * @property boolean $LocalMarketCounterOfferEnabled
 * @property boolean $LocalMarketNonSubscription
 * @property \DTS\eBaySDK\Trading\Enums\ClassifiedAdPaymentMethodEnabledCodeType $LocalMarketPaymentMethodCheckOutEnabled
 * @property integer $LocalMarketPhoneCount
 * @property boolean $LocalMarketPremiumSubscription
 * @property boolean $LocalMarketRegularSubscription
 * @property boolean $LocalMarketSellerContactDetailsEnabled
 * @property boolean $LocalMarketShippingMethodEnabled
 * @property boolean $LocalMarketSpecialitySubscription
 * @property integer $LocalMarketStreetCount
 * @property \DTS\eBaySDK\Trading\Types\AmountType $MaxFlatShippingCost
 * @property boolean $MaxFlatShippingCostCBTExempt
 * @property integer $MaxGranularFitmentCount
 * @property integer $MaxItemCompatibility
 * @property double $MinimumReservePrice
 * @property integer $MinItemCompatibility
 * @property \DTS\eBaySDK\Trading\Enums\GeographicExposureCodeType $NonSubscription
 * @property boolean $PaisaPayFullEscrowEnabled
 * @property \DTS\eBaySDK\Trading\Enums\BuyerPaymentMethodCodeType[] $PaymentMethod
 * @property \DTS\eBaySDK\Trading\Enums\PaymentOptionsGroupEnabledCodeType $PaymentOptionsGroup
 * @property \DTS\eBaySDK\Trading\Enums\ProfileCategoryGroupCodeType $PaymentProfileCategoryGroup
 * @property boolean $PayPalBuyerProtectionEnabled
 * @property boolean $PayPalRequired
 * @property boolean $PayPalRequiredForStoreOwner
 * @property boolean $PickupDropOffEnabled
 * @property \DTS\eBaySDK\Trading\Enums\GeographicExposureCodeType $PremiumSubscription
 * @property \DTS\eBaySDK\Trading\Enums\ProductCreationEnabledCodeType $ProductCreationEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ProductRequiredEnabledCodeType $ProductRequiredEnabled
 * @property boolean $ProPackEnabled
 * @property boolean $ProPackPlusEnabled
 * @property \DTS\eBaySDK\Trading\Enums\GeographicExposureCodeType $RegularSubscription
 * @property boolean $ReturnPolicyDescriptionEnabled
 * @property boolean $ReturnPolicyEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ProfileCategoryGroupCodeType $ReturnPolicyProfileCategoryGroup
 * @property boolean $RevisePriceAllowed
 * @property boolean $ReviseQuantityAllowed
 * @property boolean $SafePaymentRequired
 * @property boolean $SellerContactDetailsEnabled
 * @property boolean $SellerProvidedTitleSupported
 * @property \DTS\eBaySDK\Trading\Enums\ProfileCategoryGroupCodeType $ShippingProfileCategoryGroup
 * @property boolean $ShippingTermsRequired
 * @property boolean $SkypeMeNonTransactionalEnabled
 * @property boolean $SkypeMeTransactionalEnabled
 * @property \DTS\eBaySDK\Trading\Enums\GeographicExposureCodeType $SpecialitySubscription
 * @property \DTS\eBaySDK\Trading\Types\StoreOwnerExtendedListingDurationsType $StoreOwnerExtendedListingDurations
 * @property boolean $StoreOwnerExtendedListingDurationsEnabled
 * @property boolean $TransactionConfirmationRequestEnabled
 * @property \DTS\eBaySDK\Trading\Enums\ProductIdentiferEnabledCodeType $UPCEnabled
 * @property boolean $UPCIdentifierEnabled
 * @property boolean $UserConsentRequired
 * @property boolean $ValueCategory
 * @property boolean $ValuePackEnabled
 * @property boolean $VariationsEnabled
 * @property boolean $VINSupported
 * @property boolean $VRMSupported
 */
class SiteDefaultsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'AdditionalCompatibilityEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdditionalCompatibilityEnabled'
        ],
        'AdFormatEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdFormatEnabled'
        ],
        'BasicUpgradePackEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BasicUpgradePackEnabled'
        ],
        'BestOfferAutoAcceptEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoAcceptEnabled'
        ],
        'BestOfferAutoDeclineEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoDeclineEnabled'
        ],
        'BestOfferCounterEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferCounterEnabled'
        ],
        'BestOfferEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferEnabled'
        ],
        'BrandMPNIdentifierEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BrandMPNIdentifierEnabled'
        ],
        'BuyerGuaranteeEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerGuaranteeEnabled'
        ],
        'ClassifiedAdAutoAcceptEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdAutoAcceptEnabled'
        ],
        'ClassifiedAdAutoDeclineEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdAutoDeclineEnabled'
        ],
        'ClassifiedAdBestOfferEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdBestOfferEnabled'
        ],
        'ClassifiedAdCompanyNameEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdCompanyNameEnabled'
        ],
        'ClassifiedAdContactByAddressEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByAddressEnabled'
        ],
        'ClassifiedAdContactByEmailEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByEmailEnabled'
        ],
        'ClassifiedAdContactByPhoneEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByPhoneEnabled'
        ],
        'ClassifiedAdCounterOfferEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdCounterOfferEnabled'
        ],
        'ClassifiedAdPaymentMethodEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPaymentMethodEnabled'
        ],
        'ClassifiedAdPayPerLeadEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPayPerLeadEnabled'
        ],
        'ClassifiedAdPhoneCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPhoneCount'
        ],
        'ClassifiedAdShippingMethodEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdShippingMethodEnabled'
        ],
        'ClassifiedAdStreetCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdStreetCount'
        ],
        'CompatibleVehicleType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CompatibleVehicleType'
        ],
        'ConditionEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConditionEnabled'
        ],
        'ConditionValues' => [
            'type' => 'DTS\eBaySDK\Trading\Types\ConditionValuesType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConditionValues'
        ],
        'CrossBorderTradeAustraliaEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeAustraliaEnabled'
        ],
        'CrossBorderTradeGBEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeGBEnabled'
        ],
        'CrossBorderTradeNorthAmericaEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeNorthAmericaEnabled'
        ],
        'DepositSupported' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DepositSupported'
        ],
        'DigitalGoodDeliveryEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DigitalGoodDeliveryEnabled'
        ],
        'DomesticRefundMethodValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticRefundMethodValues'
        ],
        'DomesticReturnsAcceptedValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticReturnsAcceptedValues'
        ],
        'DomesticReturnsDurationValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticReturnsDurationValues'
        ],
        'DomesticReturnsShipmentPayeeValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticReturnsShipmentPayeeValues'
        ],
        'EANEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EANEnabled'
        ],
        'EANIdentifierEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EANIdentifierEnabled'
        ],
        'eBayMotorsProAdFormatEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAdFormatEnabled'
        ],
        'eBayMotorsProAutoAcceptEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAutoAcceptEnabled'
        ],
        'eBayMotorsProAutoDeclineEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAutoDeclineEnabled'
        ],
        'eBayMotorsProBestOfferEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProBestOfferEnabled'
        ],
        'eBayMotorsProCompanyNameEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProCompanyNameEnabled'
        ],
        'eBayMotorsProContactByAddressEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByAddressEnabled'
        ],
        'eBayMotorsProContactByEmailEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByEmailEnabled'
        ],
        'eBayMotorsProContactByPhoneEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByPhoneEnabled'
        ],
        'eBayMotorsProCounterOfferEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProCounterOfferEnabled'
        ],
        'eBayMotorsProPaymentMethodCheckOutEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProPaymentMethodCheckOutEnabled'
        ],
        'eBayMotorsProPhoneCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProPhoneCount'
        ],
        'eBayMotorsProSellerContactDetailsEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProSellerContactDetailsEnabled'
        ],
        'eBayMotorsProShippingMethodEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProShippingMethodEnabled'
        ],
        'eBayMotorsProStreetCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProStreetCount'
        ],
        'EpidSupported' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EpidSupported'
        ],
        'FreeGalleryPlusEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FreeGalleryPlusEnabled'
        ],
        'FreePicturePackEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FreePicturePackEnabled'
        ],
        'GalleryFeaturedDurations' => [
            'type' => 'DTS\eBaySDK\Trading\Types\ListingEnhancementDurationReferenceType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GalleryFeaturedDurations'
        ],
        'GlobalShippingEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GlobalShippingEnabled'
        ],
        'Group1MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group1MaxFlatShippingCost'
        ],
        'Group2MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group2MaxFlatShippingCost'
        ],
        'Group3MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group3MaxFlatShippingCost'
        ],
        'HandlingTimeEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HandlingTimeEnabled'
        ],
        'HomePageFeaturedEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HomePageFeaturedEnabled'
        ],
        'INEscrowWorkflowTimeline' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'INEscrowWorkflowTimeline'
        ],
        'InternationalRefundMethodValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalRefundMethodValues'
        ],
        'InternationalReturnsAcceptedValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalReturnsAcceptedValues'
        ],
        'InternationalReturnsDurationValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalReturnsDurationValues'
        ],
        'InternationalReturnsShipmentPayeeValues' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalReturnsShipmentPayeeValues'
        ],
        'ISBNEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ISBNEnabled'
        ],
        'ISBNIdentifierEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ISBNIdentifierEnabled'
        ],
        'ItemCompatibilityEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemCompatibilityEnabled'
        ],
        'ItemSpecificsEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemSpecificsEnabled'
        ],
        'KTypeSupported' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'KTypeSupported'
        ],
        'ListingDuration' => [
            'type' => 'DTS\eBaySDK\Trading\Types\ListingDurationReferenceType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ListingDuration'
        ],
        'LocalListingDistancesNonSubscription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesNonSubscription'
        ],
        'LocalListingDistancesRegular' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesRegular'
        ],
        'LocalListingDistancesSpecialty' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesSpecialty'
        ],
        'LocalMarketAdFormatEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAdFormatEnabled'
        ],
        'LocalMarketAutoAcceptEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAutoAcceptEnabled'
        ],
        'LocalMarketAutoDeclineEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAutoDeclineEnabled'
        ],
        'LocalMarketBestOfferEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketBestOfferEnabled'
        ],
        'LocalMarketCompanyNameEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketCompanyNameEnabled'
        ],
        'LocalMarketContactByAddressEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByAddressEnabled'
        ],
        'LocalMarketContactByEmailEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByEmailEnabled'
        ],
        'LocalMarketContactByPhoneEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByPhoneEnabled'
        ],
        'LocalMarketCounterOfferEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketCounterOfferEnabled'
        ],
        'LocalMarketNonSubscription' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketNonSubscription'
        ],
        'LocalMarketPaymentMethodCheckOutEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPaymentMethodCheckOutEnabled'
        ],
        'LocalMarketPhoneCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPhoneCount'
        ],
        'LocalMarketPremiumSubscription' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPremiumSubscription'
        ],
        'LocalMarketRegularSubscription' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketRegularSubscription'
        ],
        'LocalMarketSellerContactDetailsEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketSellerContactDetailsEnabled'
        ],
        'LocalMarketShippingMethodEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketShippingMethodEnabled'
        ],
        'LocalMarketSpecialitySubscription' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketSpecialitySubscription'
        ],
        'LocalMarketStreetCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketStreetCount'
        ],
        'MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxFlatShippingCost'
        ],
        'MaxFlatShippingCostCBTExempt' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxFlatShippingCostCBTExempt'
        ],
        'MaxGranularFitmentCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxGranularFitmentCount'
        ],
        'MaxItemCompatibility' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxItemCompatibility'
        ],
        'MinimumReservePrice' => [
            'type' => 'double',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinimumReservePrice'
        ],
        'MinItemCompatibility' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinItemCompatibility'
        ],
        'NonSubscription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'NonSubscription'
        ],
        'PaisaPayFullEscrowEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaisaPayFullEscrowEnabled'
        ],
        'PaymentMethod' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'PaymentMethod'
        ],
        'PaymentOptionsGroup' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentOptionsGroup'
        ],
        'PaymentProfileCategoryGroup' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentProfileCategoryGroup'
        ],
        'PayPalBuyerProtectionEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalBuyerProtectionEnabled'
        ],
        'PayPalRequired' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalRequired'
        ],
        'PayPalRequiredForStoreOwner' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalRequiredForStoreOwner'
        ],
        'PickupDropOffEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PickupDropOffEnabled'
        ],
        'PremiumSubscription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PremiumSubscription'
        ],
        'ProductCreationEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductCreationEnabled'
        ],
        'ProductRequiredEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductRequiredEnabled'
        ],
        'ProPackEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProPackEnabled'
        ],
        'ProPackPlusEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProPackPlusEnabled'
        ],
        'RegularSubscription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RegularSubscription'
        ],
        'ReturnPolicyDescriptionEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyDescriptionEnabled'
        ],
        'ReturnPolicyEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyEnabled'
        ],
        'ReturnPolicyProfileCategoryGroup' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyProfileCategoryGroup'
        ],
        'RevisePriceAllowed' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RevisePriceAllowed'
        ],
        'ReviseQuantityAllowed' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReviseQuantityAllowed'
        ],
        'SafePaymentRequired' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SafePaymentRequired'
        ],
        'SellerContactDetailsEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerContactDetailsEnabled'
        ],
        'SellerProvidedTitleSupported' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerProvidedTitleSupported'
        ],
        'ShippingProfileCategoryGroup' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingProfileCategoryGroup'
        ],
        'ShippingTermsRequired' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingTermsRequired'
        ],
        'SkypeMeNonTransactionalEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SkypeMeNonTransactionalEnabled'
        ],
        'SkypeMeTransactionalEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SkypeMeTransactionalEnabled'
        ],
        'SpecialitySubscription' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SpecialitySubscription'
        ],
        'StoreOwnerExtendedListingDurations' => [
            'type' => 'DTS\eBaySDK\Trading\Types\StoreOwnerExtendedListingDurationsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StoreOwnerExtendedListingDurations'
        ],
        'StoreOwnerExtendedListingDurationsEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StoreOwnerExtendedListingDurationsEnabled'
        ],
        'TransactionConfirmationRequestEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionConfirmationRequestEnabled'
        ],
        'UPCEnabled' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UPCEnabled'
        ],
        'UPCIdentifierEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UPCIdentifierEnabled'
        ],
        'UserConsentRequired' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UserConsentRequired'
        ],
        'ValueCategory' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ValueCategory'
        ],
        'ValuePackEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ValuePackEnabled'
        ],
        'VariationsEnabled' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VariationsEnabled'
        ],
        'VINSupported' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VINSupported'
        ],
        'VRMSupported' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VRMSupported'
        ]
    ];
    
    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }
        
        $this->setValues(__CLASS__, $childValues);
    }
}