<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class AccessRuleCurrentStatusCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const DailyLimitExceeded = 'DailyLimitExceeded';
    private const DailySoftLimitExceeded = 'DailySoftLimitExceeded';
    private const HourlyLimitExceeded = 'HourlyLimitExceeded';
    private const HourlySoftLimitExceeded = 'HourlySoftLimitExceeded';
    private const NotSet = 'NotSet';
    private const PeriodicLimitExceeded = 'PeriodicLimitExceeded';
    private const PeriodicSoftLimitExceeded = 'PeriodicSoftLimitExceeded';

}
