<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class AdFormatEnabledCodeType extends Enum 
{
    private const ClassifiedAdEnabled = 'ClassifiedAdEnabled';
    private const ClassifiedAdOnly = 'ClassifiedAdOnly';
    private const CustomCode = 'CustomCode';
    private const Disabled = 'Disabled';
    private const Enabled = 'Enabled';
    private const LocalMarketBestOfferOnly = 'LocalMarketBestOfferOnly';
    private const Only = 'Only';

}
