<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ApplicationDeviceTypeCodeType extends Enum 
{
    private const Browser = 'Browser';
    private const CustomCode = 'CustomCode';
    private const Desktop = 'Desktop';
    private const SetTopTVBox = 'SetTopTVBox';
    private const Wireless = 'Wireless';

}
