<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class BuyerPaymentInstrumentCodeType extends Enum 
{
    private const BankDirectDebit = 'BankDirectDebit';
    private const BML = 'BML';
    private const CreditCard = 'CreditCard';
    private const CustomCode = 'CustomCode';
    private const ELV = 'ELV';
    private const GIROPAY = 'GIROPAY';
    private const LocalPaymentAMEX = 'LocalPaymentAMEX';
    private const LocalPaymentCreditCardOther = 'LocalPaymentCreditCardOther';
    private const LocalPaymentDinersclub = 'LocalPaymentDinersclub';
    private const LocalPaymentDiscover = 'LocalPaymentDiscover';
    private const LocalPaymentELV = 'LocalPaymentELV';
    private const LocalPaymentJCB = 'LocalPaymentJCB';
    private const LocalPaymentMasterCard = 'LocalPaymentMasterCard';
    private const LocalPaymentSOLO = 'LocalPaymentSOLO';
    private const LocalPaymentSWITCH = 'LocalPaymentSWITCH';
    private const LocalPaymentVISA = 'LocalPaymentVISA';
    private const None = 'None';
    private const PayPal = 'PayPal';
    private const PayUponInvoice = 'PayUponInvoice';

}
