<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class BuyerPaymentMethodCodeType extends Enum 
{
    private const AmEx = 'AmEx';
    private const CashInPerson = 'CashInPerson';
    private const CashOnPickup = 'CashOnPickup';
    private const CCAccepted = 'CCAccepted';
    private const COD = 'COD';
    private const CODPrePayDelivery = 'CODPrePayDelivery';
    private const CreditCard = 'CreditCard';
    private const CustomCode = 'CustomCode';
    private const Diners = 'Diners';
    private const DirectDebit = 'DirectDebit';
    private const Discover = 'Discover';
    private const Escrow = 'Escrow';
    private const LoanCheck = 'LoanCheck';
    private const MOCC = 'MOCC';
    private const MoneyXferAccepted = 'MoneyXferAccepted';
    private const MoneyXferAcceptedInCheckout = 'MoneyXferAcceptedInCheckout';
    private const None = 'None';
    private const Other = 'Other';
    private const OtherOnlinePayments = 'OtherOnlinePayments';
    private const PaymentSeeDescription = 'PaymentSeeDescription';
    private const PayOnPickup = 'PayOnPickup';
    private const PayPal = 'PayPal';
    private const PayPalCredit = 'PayPalCredit';
    private const PayUponInvoice = 'PayUponInvoice';
    private const PersonalCheck = 'PersonalCheck';
    private const PostalTransfer = 'PostalTransfer';
    private const PrePayDelivery = 'PrePayDelivery';
    private const VisaMC = 'VisaMC';

}
