<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class CancelReasonCodeType extends Enum 
{
    private const BuyerCancelOrAddressIssue = 'BuyerCancelOrAddressIssue';
    private const BuyerCancelOrder = 'BuyerCancelOrder';
    private const CustomCode = 'CustomCode';
    private const FoundCheaperPrice = 'FoundCheaperPrice';
    private const OrderPlacedByMistake = 'OrderPlacedByMistake';
    private const OutOfStock = 'OutOfStock';
    private const OutOfStockOrCannotFulfill = 'OutOfStockOrCannotFulfill';
    private const PriceTooHigh = 'PriceTooHigh';
    private const WontArriveInTime = 'WontArriveInTime';

}
