<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class CheckoutStatusCodeType extends Enum 
{
    private const BuyerRequestsTotal = 'BuyerRequestsTotal';
    private const CheckoutComplete = 'CheckoutComplete';
    private const CheckoutIncomplete = 'CheckoutIncomplete';
    private const CustomCode = 'CustomCode';
    private const SellerResponded = 'SellerResponded';

}
