<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class CostGroupFlatCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Group1MaxFlatShippingCost = 'Group1MaxFlatShippingCost';
    private const Group2MaxFlatShippingCost = 'Group2MaxFlatShippingCost';
    private const Group3MaxFlatShippingCost = 'Group3MaxFlatShippingCost';

}
