<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DayOfWeekCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Friday = 'Friday';
    private const Monday = 'Monday';
    private const Saturday = 'Saturday';
    private const Sunday = 'Sunday';
    private const Thursday = 'Thursday';
    private const Tuesday = 'Tuesday';
    private const Wednesday = 'Wednesday';

}
