<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DaysCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const EveryDay = 'EveryDay';
    private const None = 'None';
    private const Weekdays = 'Weekdays';
    private const Weekends = 'Weekends';

}
