<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DiscountNameCodeType extends Enum 
{
    private const CombinedItemWeight = 'CombinedItemWeight';
    private const CustomCode = 'CustomCode';
    private const EachAdditionalAmount = 'EachAdditionalAmount';
    private const EachAdditionalAmountOff = 'EachAdditionalAmountOff';
    private const EachAdditionalPercentOff = 'EachAdditionalPercentOff';
    private const IndividualItemWeight = 'IndividualItemWeight';
    private const MaximumShippingCostPerOrder = 'MaximumShippingCostPerOrder';
    private const ShippingCostXForAmountY = 'ShippingCostXForAmountY';
    private const ShippingCostXForItemCountN = 'ShippingCostXForItemCountN';
    private const WeightOff = 'WeightOff';

}
