<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeMessageSourceCodeType extends Enum 
{
    private const Buyer = 'Buyer';
    private const CustomCode = 'CustomCode';
    private const eBay = 'eBay';
    private const Seller = 'Seller';

}
