<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeFilterTypeCodeType extends Enum 
{
    private const AllInvolvedClosedDisputes = 'AllInvolvedClosedDisputes';
    private const AllInvolvedDisputes = 'AllInvolvedDisputes';
    private const CustomCode = 'CustomCode';
    private const DisputesAwaitingMyResponse = 'DisputesAwaitingMyResponse';
    private const DisputesAwaitingOtherPartyResponse = 'DisputesAwaitingOtherPartyResponse';
    private const EligibleForCredit = 'EligibleForCredit';
    private const ItemNotReceivedDisputes = 'ItemNotReceivedDisputes';
    private const UnpaidItemDisputes = 'UnpaidItemDisputes';

}
