<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeActivityCodeType extends Enum 
{
    private const CameToAgreementNeedFVFCredit = 'CameToAgreementNeedFVFCredit';
    private const CustomCode = 'CustomCode';
    private const MutualAgreementOrNoBuyerResponse = 'MutualAgreementOrNoBuyerResponse';
    private const SellerAddInformation = 'SellerAddInformation';
    private const SellerComment = 'SellerComment';
    private const SellerCompletedTransaction = 'SellerCompletedTransaction';
    private const SellerEndCommunication = 'SellerEndCommunication';
    private const SellerOffersRefund = 'SellerOffersRefund';
    private const SellerPaymentNotReceived = 'SellerPaymentNotReceived';
    private const SellerShippedItem = 'SellerShippedItem';

}
