<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeReasonCodeType extends Enum 
{
    private const BuyerHasNotPaid = 'BuyerHasNotPaid';
    private const CustomCode = 'CustomCode';
    private const ItemNotReceived = 'ItemNotReceived';
    private const NoRefund = 'NoRefund';
    private const ReturnPolicyUnpaidItem = 'ReturnPolicyUnpaidItem';
    private const SignificantlyNotAsDescribed = 'SignificantlyNotAsDescribed';
    private const TransactionMutuallyCanceled = 'TransactionMutuallyCanceled';

}
