<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeResolutionRecordTypeCodeType extends Enum 
{
    private const AppealBuyerStrike = 'AppealBuyerStrike';
    private const CustomCode = 'CustomCode';
    private const FeatureFeeCredit = 'FeatureFeeCredit';
    private const FeatureFeeNotCredit = 'FeatureFeeNotCredit';
    private const FVFCredit = 'FVFCredit';
    private const FVFCreditNotGranted = 'FVFCreditNotGranted';
    private const FVFOnShippingCredit = 'FVFOnShippingCredit';
    private const FVFOnShippingCreditNotGranted = 'FVFOnShippingCreditNotGranted';
    private const GenerateCSTicketForSuspend = 'GenerateCSTicketForSuspend';
    private const InsertionFeeCredit = 'InsertionFeeCredit';
    private const ItemNotReceivedClaimFiled = 'ItemNotReceivedClaimFiled';
    private const RestrictBuyer = 'RestrictBuyer';
    private const ReverseFeatureFeeCredit = 'ReverseFeatureFeeCredit';
    private const ReverseFVFCredit = 'ReverseFVFCredit';
    private const ReverseFVFOnShippingCredit = 'ReverseFVFOnShippingCredit';
    private const ReverseInsertionFeeCredit = 'ReverseInsertionFeeCredit';
    private const StrikeBuyer = 'StrikeBuyer';
    private const SuspendBuyer = 'SuspendBuyer';
    private const UnpaidItemRelisted = 'UnpaidItemRelisted';
    private const UnpaidItemRevised = 'UnpaidItemRevised';
    private const UnrestrictBuyer = 'UnrestrictBuyer';
    private const UnsuspendBuyer = 'UnsuspendBuyer';

}
