<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeExplanationCodeType extends Enum 
{
    private const BuyerHasNotResponded = 'BuyerHasNotResponded';
    private const BuyerNoLongerWantsItem = 'BuyerNoLongerWantsItem';
    private const BuyerNotClearedToPay = 'BuyerNotClearedToPay';
    private const BuyerNotPaid = 'BuyerNotPaid';
    private const BuyerPaymentNotReceivedOrCleared = 'BuyerPaymentNotReceivedOrCleared';
    private const BuyerPurchasingMistake = 'BuyerPurchasingMistake';
    private const BuyerRefusedToPay = 'BuyerRefusedToPay';
    private const BuyerReturnedItemForRefund = 'BuyerReturnedItemForRefund';
    private const CustomCode = 'CustomCode';
    private const OtherExplanation = 'OtherExplanation';
    private const SellerDoesntShipToCountry = 'SellerDoesntShipToCountry';
    private const SellerRanOutOfStock = 'SellerRanOutOfStock';
    private const ShippingAddressNotConfirmed = 'ShippingAddressNotConfirmed';
    private const UnableToResolveTerms = 'UnableToResolveTerms';
    private const Unspecified = 'Unspecified';
    private const UPIAssistance = 'UPIAssistance';
    private const UPIAssistanceDisabled = 'UPIAssistanceDisabled';

}
