<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeStatusCodeType extends Enum 
{
    private const ClaimApproved = 'ClaimApproved';
    private const ClaimClosed = 'ClaimClosed';
    private const ClaimDenied = 'ClaimDenied';
    private const ClaimInProcess = 'ClaimInProcess';
    private const ClaimOpened = 'ClaimOpened';
    private const ClaimPaid = 'ClaimPaid';
    private const ClaimResolved = 'ClaimResolved';
    private const ClaimSubmitted = 'ClaimSubmitted';
    private const Closed = 'Closed';
    private const ClosedFVFCreditNoStrike = 'ClosedFVFCreditNoStrike';
    private const ClosedFVFCreditStrike = 'ClosedFVFCreditStrike';
    private const ClosedNoFVFCreditNoStrike = 'ClosedNoFVFCreditNoStrike';
    private const ClosedNoFVFCreditStrike = 'ClosedNoFVFCreditStrike';
    private const CustomCode = 'CustomCode';
    private const FVFCreditReversedAfterClosing = 'FVFCreditReversedAfterClosing';
    private const NoDocumentation = 'NoDocumentation';
    private const StrikeAppealedAfterClosing = 'StrikeAppealedAfterClosing';
    private const StrikeAppealedAndFVFCreditReversed = 'StrikeAppealedAndFVFCreditReversed';
    private const UnpaidItemOpened = 'UnpaidItemOpened';
    private const WaitingForBuyerResponse = 'WaitingForBuyerResponse';
    private const WaitingForSellerResponse = 'WaitingForSellerResponse';

}
