<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class DisputeResolutionReasonCodeType extends Enum 
{
    private const BuyerPaidAuctionFees = 'BuyerPaidAuctionFees';
    private const CameToAgreement = 'CameToAgreement';
    private const ClaimPaid = 'ClaimPaid';
    private const ComputerTechnicalProblem = 'ComputerTechnicalProblem';
    private const CustomCode = 'CustomCode';
    private const FamilyEmergency = 'FamilyEmergency';
    private const FirstInfraction = 'FirstInfraction';
    private const ItemReturned = 'ItemReturned';
    private const NoContact = 'NoContact';
    private const OtherResolution = 'OtherResolution';
    private const ProofGivenInFeedback = 'ProofGivenInFeedback';
    private const ProofOfPayment = 'ProofOfPayment';
    private const SellerReceivedPayment = 'SellerReceivedPayment';
    private const Unresolved = 'Unresolved';

}
