<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class EndReasonCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Incorrect = 'Incorrect';
    private const LostOrBroken = 'LostOrBroken';
    private const NotAvailable = 'NotAvailable';
    private const OtherListingError = 'OtherListingError';
    private const ProductDeleted = 'ProductDeleted';
    private const SellToHighBidder = 'SellToHighBidder';
    private const Sold = 'Sold';

}
