<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class FeedbackRatingDetailCodeType extends Enum 
{
    private const Communication = 'Communication';
    private const CustomCode = 'CustomCode';
    private const ItemAsDescribed = 'ItemAsDescribed';
    private const ShippingAndHandlingCharges = 'ShippingAndHandlingCharges';
    private const ShippingTime = 'ShippingTime';

}
