<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class FeedbackRatingStarCodeType extends Enum 
{
    private const Blue = 'Blue';
    private const CustomCode = 'CustomCode';
    private const Green = 'Green';
    private const GreenShooting = 'GreenShooting';
    private const None = 'None';
    private const Purple = 'Purple';
    private const PurpleShooting = 'PurpleShooting';
    private const Red = 'Red';
    private const RedShooting = 'RedShooting';
    private const SilverShooting = 'SilverShooting';
    private const Turquoise = 'Turquoise';
    private const TurquoiseShooting = 'TurquoiseShooting';
    private const Yellow = 'Yellow';
    private const YellowShooting = 'YellowShooting';

}
