<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class GalleryStatusCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const ImageNonExistent = 'ImageNonExistent';
    private const ImageProcessingError = 'ImageProcessingError';
    private const ImageReadTimeOut = 'ImageReadTimeOut';
    private const InvalidFile = 'InvalidFile';
    private const InvalidFileFormat = 'InvalidFileFormat';
    private const InvalidProtocol = 'InvalidProtocol';
    private const InvalidUrl = 'InvalidUrl';
    private const Pending = 'Pending';
    private const ServerDown = 'ServerDown';
    private const Success = 'Success';

}
