<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class HandlingNameCodeType extends Enum 
{
    private const CombinedHandlingFee = 'CombinedHandlingFee';
    private const CustomCode = 'CustomCode';
    private const EachAdditionalAmount = 'EachAdditionalAmount';
    private const EachAdditionalAmountOff = 'EachAdditionalAmountOff';
    private const EachAdditionalPercentOff = 'EachAdditionalPercentOff';
    private const IndividualHandlingFee = 'IndividualHandlingFee';

}
