<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ItemTypeCodeType extends Enum 
{
    private const AllItems = 'AllItems';
    private const AuctionItemsOnly = 'AuctionItemsOnly';
    private const ClassifiedItemsOnly = 'ClassifiedItemsOnly';
    private const CustomCode = 'CustomCode';
    private const FixedPricedItem = 'FixedPricedItem';
    private const StoreInventoryOnly = 'StoreInventoryOnly';

}
