<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ItemCompatibilityEnabledCodeType extends Enum 
{
    private const ByApplication = 'ByApplication';
    private const BySpecification = 'BySpecification';
    private const CustomCode = 'CustomCode';
    private const Disabled = 'Disabled';

}
