<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ItemSortTypeCodeType extends Enum 
{
    private const BestOffer = 'BestOffer';
    private const BestOfferCount = 'BestOfferCount';
    private const BestOfferCountDescending = 'BestOfferCountDescending';
    private const BestOfferDescending = 'BestOfferDescending';
    private const BidCount = 'BidCount';
    private const BidCountDescending = 'BidCountDescending';
    private const BidderCount = 'BidderCount';
    private const BidderCountDescending = 'BidderCountDescending';
    private const BuyerEmail = 'BuyerEmail';
    private const BuyerEmailDescending = 'BuyerEmailDescending';
    private const BuyerPostalCode = 'BuyerPostalCode';
    private const BuyerPostalCodeDescending = 'BuyerPostalCodeDescending';
    private const BuyerUserID = 'BuyerUserID';
    private const BuyerUserIDDescending = 'BuyerUserIDDescending';
    private const CurrentPrice = 'CurrentPrice';
    private const CurrentPriceDescending = 'CurrentPriceDescending';
    private const CustomCode = 'CustomCode';
    private const EndTime = 'EndTime';
    private const EndTimeDescending = 'EndTimeDescending';
    private const FeedbackLeft = 'FeedbackLeft';
    private const FeedbackLeftDescending = 'FeedbackLeftDescending';
    private const FeedbackReceived = 'FeedbackReceived';
    private const FeedbackReceivedDescending = 'FeedbackReceivedDescending';
    private const HighBidderUserID = 'HighBidderUserID';
    private const HighBidderUserIDDescending = 'HighBidderUserIDDescending';
    private const ItemID = 'ItemID';
    private const ItemIDDescending = 'ItemIDDescending';
    private const LeadCount = 'LeadCount';
    private const LeadCountDescending = 'LeadCountDescending';
    private const ListingDuration = 'ListingDuration';
    private const ListingDurationDescending = 'ListingDurationDescending';
    private const ListingType = 'ListingType';
    private const ListingTypeDescending = 'ListingTypeDescending';
    private const MaxBid = 'MaxBid';
    private const MaxBidDescending = 'MaxBidDescending';
    private const NewLeadCount = 'NewLeadCount';
    private const NewLeadCountDescending = 'NewLeadCountDescending';
    private const Price = 'Price';
    private const PriceDescending = 'PriceDescending';
    private const Quantity = 'Quantity';
    private const QuantityAvailable = 'QuantityAvailable';
    private const QuantityAvailableDescending = 'QuantityAvailableDescending';
    private const QuantityDescending = 'QuantityDescending';
    private const QuantityPurchased = 'QuantityPurchased';
    private const QuantityPurchasedDescending = 'QuantityPurchasedDescending';
    private const QuantitySold = 'QuantitySold';
    private const QuantitySoldDescending = 'QuantitySoldDescending';
    private const QuestionCount = 'QuestionCount';
    private const QuestionCountDescending = 'QuestionCountDescending';
    private const ReservePrice = 'ReservePrice';
    private const ReservePriceDescending = 'ReservePriceDescending';
    private const SellerEmail = 'SellerEmail';
    private const SellerEmailDescending = 'SellerEmailDescending';
    private const SellerUserID = 'SellerUserID';
    private const SellerUserIDDescending = 'SellerUserIDDescending';
    private const ShippingServiceCost = 'ShippingServiceCost';
    private const ShippingServiceCostDescending = 'ShippingServiceCostDescending';
    private const StartPrice = 'StartPrice';
    private const StartPriceDescending = 'StartPriceDescending';
    private const StartTime = 'StartTime';
    private const StartTimeDescending = 'StartTimeDescending';
    private const TimeLeft = 'TimeLeft';
    private const TimeLeftDescending = 'TimeLeftDescending';
    private const Title = 'Title';
    private const TitleDescending = 'TitleDescending';
    private const TotalPrice = 'TotalPrice';
    private const TotalPriceDescending = 'TotalPriceDescending';
    private const UserID = 'UserID';
    private const UserIDDescending = 'UserIDDescending';
    private const WatchCount = 'WatchCount';
    private const WatchCountDescending = 'WatchCountDescending';

}
