<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ListingDurationCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Days_1 = 'Days_1';
    private const Days_10 = 'Days_10';
    private const Days_120 = 'Days_120';
    private const Days_14 = 'Days_14';
    private const Days_21 = 'Days_21';
    private const Days_3 = 'Days_3';
    private const Days_30 = 'Days_30';
    private const Days_5 = 'Days_5';
    private const Days_60 = 'Days_60';
    private const Days_7 = 'Days_7';
    private const Days_90 = 'Days_90';
    private const GTC = 'GTC';

}
