<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ModifyActionCodeType extends Enum 
{
    private const Add = 'Add';
    private const CustomCode = 'CustomCode';
    private const Delete = 'Delete';
    private const Update = 'Update';

}
