<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class NotificationEventTypeCodeType extends Enum 
{
    private const AccountSummary = 'AccountSummary';
    private const AccountSuspended = 'AccountSuspended';
    private const AskSellerQuestion = 'AskSellerQuestion';
    private const AuctionCheckoutComplete = 'AuctionCheckoutComplete';
    private const BestOffer = 'BestOffer';
    private const BestOfferDeclined = 'BestOfferDeclined';
    private const BestOfferPlaced = 'BestOfferPlaced';
    private const BidItemEndingSoon = 'BidItemEndingSoon';
    private const BidPlaced = 'BidPlaced';
    private const BidReceived = 'BidReceived';
    private const BulkDataExchangeJobCompleted = 'BulkDataExchangeJobCompleted';
    private const BuyerCancelRequested = 'BuyerCancelRequested';
    private const BuyerNoShow = 'BuyerNoShow';
    private const BuyerResponseDispute = 'BuyerResponseDispute';
    private const CheckoutBuyerRequestsTotal = 'CheckoutBuyerRequestsTotal';
    private const CounterOfferReceived = 'CounterOfferReceived';
    private const CustomCode = 'CustomCode';
    private const EBNOrderCanceled = 'EBNOrderCanceled';
    private const EBNOrderPickedUp = 'EBNOrderPickedUp';
    private const EBPAppealedCase = 'EBPAppealedCase';
    private const EBPClosedAppeal = 'EBPClosedAppeal';
    private const EBPClosedCase = 'EBPClosedCase';
    private const EBPEscalatedCase = 'EBPEscalatedCase';
    private const EBPMyPaymentDue = 'EBPMyPaymentDue';
    private const EBPMyResponseDue = 'EBPMyResponseDue';
    private const EBPOnHoldCase = 'EBPOnHoldCase';
    private const EBPOtherPartyResponseDue = 'EBPOtherPartyResponseDue';
    private const EBPPaymentDone = 'EBPPaymentDone';
    private const EmailAddressChanged = 'EmailAddressChanged';
    private const EndOfAuction = 'EndOfAuction';
    private const Feedback = 'Feedback';
    private const FeedbackLeft = 'FeedbackLeft';
    private const FeedbackReceived = 'FeedbackReceived';
    private const FeedbackStarChanged = 'FeedbackStarChanged';
    private const FixedPriceTransaction = 'FixedPriceTransaction';
    private const INRBuyerClosedDispute = 'INRBuyerClosedDispute';
    private const INRBuyerOpenedDispute = 'INRBuyerOpenedDispute';
    private const INRBuyerRespondedToDispute = 'INRBuyerRespondedToDispute';
    private const INRSellerRespondedToDispute = 'INRSellerRespondedToDispute';
    private const ItemAddedToWatchList = 'ItemAddedToWatchList';
    private const ItemClosed = 'ItemClosed';
    private const ItemExtended = 'ItemExtended';
    private const ItemListed = 'ItemListed';
    private const ItemLost = 'ItemLost';
    private const ItemMarkedPaid = 'ItemMarkedPaid';
    private const ItemMarkedShipped = 'ItemMarkedShipped';
    private const ItemOutOfStock = 'ItemOutOfStock';
    private const ItemReadyForPickup = 'ItemReadyForPickup';
    private const ItemRemovedFromWatchList = 'ItemRemovedFromWatchList';
    private const ItemRevised = 'ItemRevised';
    private const ItemRevisedAddCharity = 'ItemRevisedAddCharity';
    private const ItemSold = 'ItemSold';
    private const ItemSuspended = 'ItemSuspended';
    private const ItemUnsold = 'ItemUnsold';
    private const ItemWon = 'ItemWon';
    private const M2MMessageStatusChange = 'M2MMessageStatusChange';
    private const MyMessageseBayMessage = 'MyMessageseBayMessage';
    private const MyMessageseBayMessageHeader = 'MyMessageseBayMessageHeader';
    private const MyMessagesHighPriorityMessage = 'MyMessagesHighPriorityMessage';
    private const MyMessagesHighPriorityMessageHeader = 'MyMessagesHighPriorityMessageHeader';
    private const MyMessagesM2MMessage = 'MyMessagesM2MMessage';
    private const MyMessagesM2MMessageHeader = 'MyMessagesM2MMessageHeader';
    private const None = 'None';
    private const OrderInquiryClosed = 'OrderInquiryClosed';
    private const OrderInquiryEscalatedToCase = 'OrderInquiryEscalatedToCase';
    private const OrderInquiryOpened = 'OrderInquiryOpened';
    private const OrderInquiryProvideShipmentInformation = 'OrderInquiryProvideShipmentInformation';
    private const OrderInquiryReminderForEscalation = 'OrderInquiryReminderForEscalation';
    private const OutBid = 'OutBid';
    private const PasswordChanged = 'PasswordChanged';
    private const PasswordHintChanged = 'PasswordHintChanged';
    private const PaymentDetailChanged = 'PaymentDetailChanged';
    private const PaymentReminder = 'PaymentReminder';
    private const ReturnClosed = 'ReturnClosed';
    private const ReturnCreated = 'ReturnCreated';
    private const ReturnDelivered = 'ReturnDelivered';
    private const ReturnEscalated = 'ReturnEscalated';
    private const ReturnRefundOverdue = 'ReturnRefundOverdue';
    private const ReturnSellerInfoOverdue = 'ReturnSellerInfoOverdue';
    private const ReturnShipped = 'ReturnShipped';
    private const ReturnWaitingForSellerInfo = 'ReturnWaitingForSellerInfo';
    private const SecondChanceOffer = 'SecondChanceOffer';
    private const SellerClosedDispute = 'SellerClosedDispute';
    private const SellerOpenedDispute = 'SellerOpenedDispute';
    private const SellerRespondedToDispute = 'SellerRespondedToDispute';
    private const ShoppingCartItemEndingSoon = 'ShoppingCartItemEndingSoon';
    private const TokenRevocation = 'TokenRevocation';
    private const UserIDChanged = 'UserIDChanged';
    private const WatchedItemEndingSoon = 'WatchedItemEndingSoon';
    private const WebnextMobilePhotoSync = 'WebnextMobilePhotoSync';

}
