<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PaidStatusCodeType extends Enum 
{
    private const BuyerHasNotCompletedCheckout = 'BuyerHasNotCompletedCheckout';
    private const CustomCode = 'CustomCode';
    private const MarkedAsPaid = 'MarkedAsPaid';
    private const NotPaid = 'NotPaid';
    private const Paid = 'Paid';
    private const PaidCOD = 'PaidCOD';
    private const PaidWithPaisaPayEscrow = 'PaidWithPaisaPayEscrow';
    private const PaidWithPayPal = 'PaidWithPayPal';
    private const PaymentPending = 'PaymentPending';
    private const PaymentPendingWithPaisaPayEscrow = 'PaymentPendingWithPaisaPayEscrow';
    private const PaymentPendingWithPayPal = 'PaymentPendingWithPayPal';
    private const PayUponInvoice = 'PayUponInvoice';
    private const Refunded = 'Refunded';
    private const WaitingForCODPayment = 'WaitingForCODPayment';

}
