<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PaymentHoldStatusCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const MerchantHold = 'MerchantHold';
    private const NewSellerHold = 'NewSellerHold';
    private const None = 'None';
    private const PaymentHold = 'PaymentHold';
    private const PaymentReview = 'PaymentReview';
    private const ReleaseConfirmed = 'ReleaseConfirmed';
    private const Released = 'Released';
    private const ReleasePending = 'ReleasePending';

}
