<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PaymentStatusCodeType extends Enum 
{
    private const BuyerCreditCardFailed = 'BuyerCreditCardFailed';
    private const BuyerECheckBounced = 'BuyerECheckBounced';
    private const BuyerFailedPaymentReportedBySeller = 'BuyerFailedPaymentReportedBySeller';
    private const CustomCode = 'CustomCode';
    private const NoPaymentFailure = 'NoPaymentFailure';
    private const PaymentInProcess = 'PaymentInProcess';
    private const PayPalPaymentInProcess = 'PayPalPaymentInProcess';

}
