<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PaymentHoldReasonCodeType extends Enum 
{
    private const BelowStandardSeller = 'BelowStandardSeller';
    private const CasualSeller = 'CasualSeller';
    private const CustomCode = 'CustomCode';
    private const EbpCaseOpen = 'EbpCaseOpen';
    private const NewPaypalAccountAdded = 'NewPaypalAccountAdded';
    private const NewSeller = 'NewSeller';
    private const NotAvailable = 'NotAvailable';
    private const Other = 'Other';
    private const ReinstatementAfterSuspension = 'ReinstatementAfterSuspension';

}
