<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PayPalAccountTypeCodeType extends Enum 
{
    private const Business = 'Business';
    private const CustomCode = 'CustomCode';
    private const Invalid = 'Invalid';
    private const Personal = 'Personal';
    private const Premier = 'Premier';
    private const Unknown = 'Unknown';

}
