<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PickupStatusCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Invalid = 'Invalid';
    private const NotApplicable = 'NotApplicable';
    private const PendingMerchantConfirmation = 'PendingMerchantConfirmation';
    private const Pickedup = 'Pickedup';
    private const PickupCancelled = 'PickupCancelled';
    private const PickupCancelledBuyerNoShow = 'PickupCancelledBuyerNoShow';
    private const PickupCancelledBuyerRejected = 'PickupCancelledBuyerRejected';
    private const PickupCancelledOutOfStock = 'PickupCancelledOutOfStock';
    private const ReadyToPickup = 'ReadyToPickup';

}
