<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class PictureUploadPolicyCodeType extends Enum 
{
    private const Add = 'Add';
    private const ClearAndAdd = 'ClearAndAdd';
    private const CustomCode = 'CustomCode';

}
