<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ReturnsWithinOptionsCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Days_14 = 'Days_14';
    private const Days_30 = 'Days_30';
    private const Days_60 = 'Days_60';

}
