<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ReturnStatusCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Invalid = 'Invalid';
    private const NotApplicable = 'NotApplicable';
    private const ReturnClosedEscalated = 'ReturnClosedEscalated';
    private const ReturnClosedNoRefund = 'ReturnClosedNoRefund';
    private const ReturnClosedWithRefund = 'ReturnClosedWithRefund';
    private const ReturnDelivered = 'ReturnDelivered';
    private const ReturnEscalated = 'ReturnEscalated';
    private const ReturnEscalatedClosedNoRefund = 'ReturnEscalatedClosedNoRefund';
    private const ReturnEscalatedClosedWithRefund = 'ReturnEscalatedClosedWithRefund';
    private const ReturnEscalatedPendingBuyer = 'ReturnEscalatedPendingBuyer';
    private const ReturnEscalatedPendingCS = 'ReturnEscalatedPendingCS';
    private const ReturnEscalatedPendingSeller = 'ReturnEscalatedPendingSeller';
    private const ReturnOpen = 'ReturnOpen';
    private const ReturnRequestClosedNoRefund = 'ReturnRequestClosedNoRefund';
    private const ReturnRequestClosedWithRefund = 'ReturnRequestClosedWithRefund';
    private const ReturnRequestPending = 'ReturnRequestPending';
    private const ReturnRequestPendingApproval = 'ReturnRequestPendingApproval';
    private const ReturnRequestRejected = 'ReturnRequestRejected';
    private const ReturnShipped = 'ReturnShipped';

}
