<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SecondChanceOfferDurationCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Days_1 = 'Days_1';
    private const Days_3 = 'Days_3';
    private const Days_5 = 'Days_5';
    private const Days_7 = 'Days_7';

}
