<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellerLevelCodeType extends Enum 
{
    private const Bronze = 'Bronze';
    private const CustomCode = 'CustomCode';
    private const Gold = 'Gold';
    private const None = 'None';
    private const Platinum = 'Platinum';
    private const Silver = 'Silver';
    private const Titanium = 'Titanium';

}
