<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellerPaymentMethodCodeType extends Enum 
{
    private const CreditCard = 'CreditCard';
    private const CustomCode = 'CustomCode';
    private const DirectDebit = 'DirectDebit';
    private const DirectDebitPendingSignatureMandate = 'DirectDebitPendingSignatureMandate';
    private const DirectDebitPendingVerification = 'DirectDebitPendingVerification';
    private const eBayDirectPay = 'eBayDirectPay';
    private const NothingOnFile = 'NothingOnFile';
    private const PayPal = 'PayPal';

}
