<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerEmailTypeCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const CustomEmailTemplate1 = 'CustomEmailTemplate1';
    private const CustomEmailTemplate10 = 'CustomEmailTemplate10';
    private const CustomEmailTemplate11 = 'CustomEmailTemplate11';
    private const CustomEmailTemplate12 = 'CustomEmailTemplate12';
    private const CustomEmailTemplate13 = 'CustomEmailTemplate13';
    private const CustomEmailTemplate14 = 'CustomEmailTemplate14';
    private const CustomEmailTemplate15 = 'CustomEmailTemplate15';
    private const CustomEmailTemplate16 = 'CustomEmailTemplate16';
    private const CustomEmailTemplate17 = 'CustomEmailTemplate17';
    private const CustomEmailTemplate18 = 'CustomEmailTemplate18';
    private const CustomEmailTemplate19 = 'CustomEmailTemplate19';
    private const CustomEmailTemplate2 = 'CustomEmailTemplate2';
    private const CustomEmailTemplate20 = 'CustomEmailTemplate20';
    private const CustomEmailTemplate3 = 'CustomEmailTemplate3';
    private const CustomEmailTemplate4 = 'CustomEmailTemplate4';
    private const CustomEmailTemplate5 = 'CustomEmailTemplate5';
    private const CustomEmailTemplate6 = 'CustomEmailTemplate6';
    private const CustomEmailTemplate7 = 'CustomEmailTemplate7';
    private const CustomEmailTemplate8 = 'CustomEmailTemplate8';
    private const CustomEmailTemplate9 = 'CustomEmailTemplate9';
    private const FeedbackReminderEmail = 'FeedbackReminderEmail';
    private const InvoiceNotification = 'InvoiceNotification';
    private const ManualEntry = 'ManualEntry';
    private const PaymentReceivedEmail = 'PaymentReceivedEmail';
    private const PaymentReminderEmail = 'PaymentReminderEmail';
    private const PersonalizedEmail = 'PersonalizedEmail';
    private const RequestForShippingAddressEmail = 'RequestForShippingAddressEmail';
    private const ShipmentSentEmail = 'ShipmentSentEmail';
    private const WinningBuyerEmail = 'WinningBuyerEmail';

}
