<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerAutoSecondChanceOfferTypeCodeType extends Enum 
{
    private const BidsGreaterThanAmount = 'BidsGreaterThanAmount';
    private const BidsGreaterThanCostPlusAmount = 'BidsGreaterThanCostPlusAmount';
    private const BidsGreaterThanCostPlusPercentage = 'BidsGreaterThanCostPlusPercentage';
    private const CustomCode = 'CustomCode';

}
