<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerInventoryPropertyTypeCodeType extends Enum 
{
    private const Active = 'Active';
    private const CustomCode = 'CustomCode';
    private const InActive = 'InActive';
    private const LowStock = 'LowStock';
    private const ProductsOutOfStock = 'ProductsOutOfStock';
    private const WithListings = 'WithListings';
    private const WithoutListings = 'WithoutListings';

}
