<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerAutoRelistOptionCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const RelistAfterDaysHours = 'RelistAfterDaysHours';
    private const RelistAtSpecificTimeOfDay = 'RelistAtSpecificTimeOfDay';
    private const RelistImmediately = 'RelistImmediately';

}
