<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerSoldListingsSortTypeCodeType extends Enum 
{
    private const BuyerEmail = 'BuyerEmail';
    private const BuyerPostalCode = 'BuyerPostalCode';
    private const CheckoutState = 'CheckoutState';
    private const CustomCode = 'CustomCode';
    private const CustomLabel = 'CustomLabel';
    private const DaysSinceSale = 'DaysSinceSale';
    private const EmailsSent = 'EmailsSent';
    private const FeedbackLeft = 'FeedbackLeft';
    private const FeedbackReceived = 'FeedbackReceived';
    private const ListedOn = 'ListedOn';
    private const PaidDate = 'PaidDate';
    private const PaidState = 'PaidState';
    private const ReservePrice = 'ReservePrice';
    private const SaleDate = 'SaleDate';
    private const SaleFormat = 'SaleFormat';
    private const SalesRecordID = 'SalesRecordID';
    private const ShippedDate = 'ShippedDate';
    private const ShippedState = 'ShippedState';
    private const ShippingCost = 'ShippingCost';
    private const SoldOn = 'SoldOn';
    private const StartPrice = 'StartPrice';
    private const TotalPrice = 'TotalPrice';

}
