<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SellingManagerProductSortCodeType extends Enum 
{
    private const ActiveQuantity = 'ActiveQuantity';
    private const AvailableToList = 'AvailableToList';
    private const AveragePrice = 'AveragePrice';
    private const AverageUnitCost = 'AverageUnitCost';
    private const CustomCode = 'CustomCode';
    private const CustomLabel = 'CustomLabel';
    private const FolderName = 'FolderName';
    private const LastSubmittedDate = 'LastSubmittedDate';
    private const ProductName = 'ProductName';
    private const ScheduledQuantity = 'ScheduledQuantity';
    private const SoldQuantity = 'SoldQuantity';
    private const SuccessPercent = 'SuccessPercent';
    private const UnsoldQuantity = 'UnsoldQuantity';

}
