<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ShippingRegionCodeType extends Enum 
{
    private const Africa = 'Africa';
    private const Americas = 'Americas';
    private const Asia = 'Asia';
    private const Caribbean = 'Caribbean';
    private const CustomCode = 'CustomCode';
    private const Europe = 'Europe';
    private const EuropeanUnion = 'EuropeanUnion';
    private const LatinAmerica = 'LatinAmerica';
    private const MiddleEast = 'MiddleEast';
    private const None = 'None';
    private const NorthAmerica = 'NorthAmerica';
    private const Oceania = 'Oceania';
    private const SouthAmerica = 'SouthAmerica';
    private const WillNotShip = 'WillNotShip';
    private const Worldwide = 'Worldwide';

}
