<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ShipmentDeliveryStatusCodeType extends Enum 
{
    private const Canceled = 'Canceled';
    private const Created = 'Created';
    private const CustomCode = 'CustomCode';
    private const Delivered = 'Delivered';
    private const DroppedOff = 'DroppedOff';
    private const Error = 'Error';
    private const InTransit = 'InTransit';
    private const LabelPrinted = 'LabelPrinted';
    private const Returned = 'Returned';
    private const Unconfirmed = 'Unconfirmed';
    private const Unknown = 'Unknown';

}
