<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SiteCodeType extends Enum 
{
    private const Australia = 'Australia';
    private const Austria = 'Austria';
    private const Belgium_Dutch = 'Belgium_Dutch';
    private const Belgium_French = 'Belgium_French';
    private const Canada = 'Canada';
    private const CanadaFrench = 'CanadaFrench';
    private const CustomCode = 'CustomCode';
    private const eBayMotors = 'eBayMotors';
    private const France = 'France';
    private const Germany = 'Germany';
    private const HongKong = 'HongKong';
    private const India = 'India';
    private const Ireland = 'Ireland';
    private const Italy = 'Italy';
    private const Malaysia = 'Malaysia';
    private const Netherlands = 'Netherlands';
    private const Philippines = 'Philippines';
    private const Poland = 'Poland';
    private const Russia = 'Russia';
    private const Singapore = 'Singapore';
    private const Spain = 'Spain';
    private const Switzerland = 'Switzerland';
    private const UK = 'UK';
    private const US = 'US';

}
