<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SMSSubscriptionUserStatusCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const Failed = 'Failed';
    private const Pending = 'Pending';
    private const Registered = 'Registered';
    private const Unregistered = 'Unregistered';

}
