<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class StoreItemListSortOrderCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const EndingFirst = 'EndingFirst';
    private const HighestPriced = 'HighestPriced';
    private const HighestPricedPlusShipping = 'HighestPricedPlusShipping';
    private const LowestPriced = 'LowestPriced';
    private const LowestPricedPlusShipping = 'LowestPricedPlusShipping';
    private const NewlyListed = 'NewlyListed';

}
