<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class StoreCustomListingHeaderLinkCodeType extends Enum 
{
    private const AboutMePage = 'AboutMePage';
    private const CustomCategory = 'CustomCategory';
    private const CustomCode = 'CustomCode';
    private const CustomPage = 'CustomPage';
    private const None = 'None';

}
