<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class StoreFontSizeCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const L = 'L';
    private const M = 'M';
    private const S = 'S';
    private const XL = 'XL';
    private const XS = 'XS';
    private const XXL = 'XXL';
    private const XXS = 'XXS';

}
