<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class SummaryWindowPeriodCodeType extends Enum 
{
    private const CurrentMonth = 'CurrentMonth';
    private const CurrentWeek = 'CurrentWeek';
    private const CustomCode = 'CustomCode';
    private const Last24Hours = 'Last24Hours';
    private const Last31Days = 'Last31Days';
    private const Last60Days = 'Last60Days';
    private const Last7Days = 'Last7Days';
    private const LastMonth = 'LastMonth';
    private const LastWeek = 'LastWeek';

}
