<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class UnpaidItemCaseOpenTypeCodeType extends Enum 
{
    private const Auto = 'Auto';
    private const CustomCode = 'CustomCode';
    private const Manual = 'Manual';

}
