<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class URLTypeCodeType extends Enum 
{
    private const AppealProductUrl = 'AppealProductUrl';
    private const CreateProductUrl = 'CreateProductUrl';
    private const CustomCode = 'CustomCode';
    private const eBayStoreURL = 'eBayStoreURL';
    private const LargeLogoURL = 'LargeLogoURL';
    private const ManageProductUrl = 'ManageProductUrl';
    private const MediumLogoURL = 'MediumLogoURL';
    private const MyeBayBiddingURL = 'MyeBayBiddingURL';
    private const MyeBayNotWonURL = 'MyeBayNotWonURL';
    private const MyeBayURL = 'MyeBayURL';
    private const MyeBayWatchingURL = 'MyeBayWatchingURL';
    private const MyeBayWonURL = 'MyeBayWonURL';
    private const SmallLogoURL = 'SmallLogoURL';
    private const ViewItemURL = 'ViewItemURL';
    private const ViewUserURL = 'ViewUserURL';

}
