<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ValueFormatCodeType extends Enum 
{
    private const CustomCode = 'CustomCode';
    private const FullDate = 'FullDate';
    private const PartialDate = 'PartialDate';
    private const Year = 'Year';

}
