<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class ValueTypeCodeType extends Enum 
{
    private const CEDULA = 'CEDULA';
    private const CNPJ = 'CNPJ';
    private const CodiceFiscale = 'CodiceFiscale';
    private const CPFTaxID = 'CPFTaxID';
    private const CustomCode = 'CustomCode';
    private const Date = 'Date';
    private const Decimal = 'Decimal';
    private const DNI = 'DNI';
    private const DriverLicense = 'DriverLicense';
    private const EAN = 'EAN';
    private const ISBN = 'ISBN';
    private const NIE = 'NIE';
    private const NIF = 'NIF';
    private const NIT = 'NIT';
    private const Numeric = 'Numeric';
    private const RussianPassport = 'RussianPassport';
    private const Text = 'Text';
    private const TurkeyID = 'TurkeyID';
    private const UPC = 'UPC';

}
