<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

use MyCLabs\Enum\Enum;

class WirelessCarrierIDCodeType extends Enum 
{
    private const ATT = 'ATT';
    private const CincinnatiBell = 'CincinnatiBell';
    private const CustomCode = 'CustomCode';
    private const Movistar = 'Movistar';
    private const Nextel = 'Nextel';
    private const Sprint = 'Sprint';
    private const TMobile = 'TMobile';
    private const USCellular = 'USCellular';
    private const Verizon = 'Verizon';
    private const Vodafone = 'Vodafone';

}
